[package]
name = "gravity_utils"
version = "0.1.0"
authors = ["Justin Kilpatrick <justin@althea.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gravity_abi = { path = "../gravity_abi" }
gravity_proto = { path = "../gravity_proto" }
cosmos-sdk-proto = "0.6.3"
deep_space = { git = "https://github.com/sankofa-foundation/deep_space/", branch = "update/deps" }
ethers = { version = "1", features = ["abigen"] }
web30 = "0.15"
clarity = "0.4.11"
lazy_static = "1.4.0"
num256 = "0.3"
serde_derive = "1.0"
serde_json = "1.0.69"
serde = "1.0"
tokio = "1.4"
tonic = { version = "0.4.0", features = ["tls", "tls-roots"] }
num-bigint = "0.4"
log = "0.4"
url = "2"
sha3 = "0.9"
tiny-bip39 = "0.8.0"
bitcoin = { version = "=0.27", features = ["use-serde"] }
hdpath = { version = "0.6.0", features = ["with-bitcoin"] }
rustc-hex = "2.1.0"
strum = "0.24"
strum_macros = "0.24"

[dev_dependencies]
rand = "0.8"
actix = "0.12"
