[package]
name = "gorc"
authors = []
version = "2.0.1"
edition = "2021"
rust-version = "1.58"

[dependencies]
aws-config = "0.47"
aws-sdk-kms = "0.17"
async-trait = "0.1"
tracing = "0.1"
spki = "0.6"
hex = "0.4"
clap = "3"
serde = { version = "1", features = ["serde_derive"] }
serde-enum-str = "0.2.5"
thiserror = "1"
regex = "1.5.4"

cosmos_gravity = { path = "../cosmos_gravity" }
ethereum_gravity = { path = "../ethereum_gravity" }
gravity_proto = { path = "../gravity_proto" }
gravity_utils = { path = "../gravity_utils" }
orchestrator = { path = "../orchestrator" }
relayer = { path = "../relayer" }

deep_space = { git = "https://github.com/sankofa-foundation/deep_space/", branch = "update/deps" }
ethers = { version = "1", features = ["abigen"] }
clarity = "0.4.12"
actix-rt = "2.5"
rpassword = "5"
bip32 = "0.4"
k256 = { version = "0.11", features = ["pem"] }
pkcs8 = { version = "0.9", features = ["pem", "alloc"] }
signatory = "0.26.0"
rand_core = { version = "0.6", features = ["std"] }
openssl-probe = "0.1.4"

abscissa_tokio = { version = "0.6.0-rc.0", features = ["actix"] }
web30 = "0.15"
tokio = "1"
tonic = { version = "0.4.0", features = ["tls", "tls-roots"] }
toml = "0.5"
env_logger = "0.8"
log = "0.4"

prost = "0.7"
bytes = "1"
proc-macro2 = "1.0.28"

[dependencies.abscissa_core]
version = "0.6.0-rc.0"
# optional: use `gimli` to capture backtraces
# see https://github.com/rust-lang/backtrace-rs/issues/189
# features = ["gimli-backtrace"]

[dev-dependencies]
abscissa_core = { version = "0.6.0-rc.0", features = ["testing"] }
once_cell = "1.2"

[features]
ethermint = ["cosmos_gravity/ethermint", "orchestrator/ethermint", "relayer/ethermint"]
